-- Table: public.BRIDGE_INFO

-- DROP TABLE IF EXISTS public."BRIDGE_INFO";

CREATE TABLE IF NOT EXISTS public."BRIDGE_INFO"
(
    objectid integer NOT NULL,
    state_code_001 character varying NOT NULL,
    structure_number_008 character varying NOT NULL,
    record_type_005a integer NOT NULL,
    route_prefix_005b integer NOT NULL,
    service_level_005c integer NOT NULL,
    route_number_005d character varying NOT NULL,
    direction_005e integer NOT NULL,
    highway_district_002 character varying,
    county_code_003 character varying NOT NULL,
    place_code_004 character varying NOT NULL,
    features_desc_006a character varying,
    critical_facility_006b character varying,
    facility_carried_007 character varying,
    location_009 character varying,
    min_vert_clr_010 double precision,
    kilopoint_011 double precision,
    base_hwy_network_012 double precision,
    lrs_inv_route_013a character varying,
    subroute_no_013b double precision,
    lat_016 double precision,
    long_017 double precision,
    detour_kilos_019 integer,
    toll_020 integer,
    maintenance_021 character varying,
    owner_022 integer NOT NULL,
    functional_class_026 character varying NOT NULL,
    year_built_027 integer NOT NULL,
    traffic_lanes_on_028a integer NOT NULL,
    traffic_lanes_und_028B integer NOT NULL,
    adt_029 bigint NOT NULL,
    year_adt_030 double precision,
    design_load_031 character varying NOT NULL,
    appr_width_mt_032 double precision NOT NULL,
    median_code_033 integer NOT NULL,
    degrees_skew_034 integer NOT NULL,
    structure_flared_035 integer NOT NULL,
    railings_036a character varying NOT NULL,
    transitions_036b character varying,
    appr_rail_036c character varying,
    appr_rail_end_036d character varying,
    history_037 integer NOT NULL,
    navigation_038 character varying,
    nav_vert_clr_mt_039 double precision,
    nav_horr_clr_mt_040 double precision,
    open_closed_posted_041 character varying,
    service_on_042a integer NOT NULL,
    service_und_042b integer NOT NULL,
    structure_kind_043a integer NOT NULL,
    structure_type_043b integer NOT NULL,
    appr_kind_044a integer NOT NULL,
    apr_type_044b integer NOT NULL,
    main_unit_spans_045 integer NOT NULL,
    appr_spans_046 integer NOT NULL,
    horr_clr_mt_047 double precision NOT NULL,
    max_span_len_mt_048 double precision NOT NULL,
    structure_len_mt_049 double precision NOT NULL,
    left_curb_mt_050a double precision NOT NULL,
    right_curb_mt_050b double precision NOT NULL,
    roadway_width_mt_051 double precision NOT NULL,
    deck_width_mt_052 double precision NOT NULL,
    vert_clr_over_mt_053 double precision NOT NULL,
    vert_clr_und_ref_054a character varying NOT NULL,
    vert_clr_und_054b double precision NOT NULL,
    lat_und_ref_055a character varying NOT NULL,
    lat_und_mt_055b double precision NOT NULL,
    left_lat_und_mt_056 double precision NOT NULL,
    deck_cond_058 character varying NOT NULL,
    superstructure_cond_059 character varying NOT NULL,
    substructure_cond_060 character varying NOT NULL,
    channel_cond_061 character varying NOT NULL,
    culvert_cond_062 character varying NOT NULL,
    opr_rating_meth_063 character varying,
    operating_rating_064 double precision,
    inv_rating_meth_065 character varying,
    inventory_rating_066 double precision,
    structural_eval_067 character varying NOT NULL,
    deck_geometry_eval_068 character varying NOT NULL,
    undclrence_eval_069 character varying NOT NULL,
    posting_eval_070 double precision,
    waterway_eval_071 character varying NOT NULL,
    appr_road_eval_072 double precision,
    work_proposed_075a double precision,
    work_done_by_075b double precision,
    imp_len_mt_076 double precision,
    date_of_inspect_090 integer NOT NULL,
    inspect_freq_months_091 integer NOT NULL,
    fracture_092a character varying NOT NULL,
    undwater_look_see_092b character varying NOT NULL,
    spec_inspect_092c character varying NOT NULL,
    fracture_last_date_093a character varying,
    undwater_last_date_093b character varying,
    spec_last_date_093c character varying,
    bridge_imp_cost_094 double precision,
    roadway_imp_cost_095 double precision,
    total_imp_cost_096 double precision,
    year_of_imp_097 double precision,
    other_state_code_098a character varying,
    other_state_pcnt_098b double precision,
    othr_state_struc_no_099 character varying,
    strahnet_highway_100 integer NOT NULL,
    parallel_structure_101 character varying,
    traffic_direction_102 integer NOT NULL,
    temp_structure_103 character varying,
    highway_system_104 integer NOT NULL,
    federal_lands_105 integer NOT NULL,
    year_reconstructed_106 double precision,
    deck_structure_type_107 character varying NOT NULL,
    surface_type_108a character varying,
    membrane_type_108b character varying,
    deck_protection_108c character varying,
    percent_adt_truck_109 double precision,
    national_network_110 integer NOT NULL,
    pier_protection_111 double precision,
    bridge_len_ind_112 character varying NOT NULL,
    scour_critical_113 character varying NOT NULL,
    future_adt_114 int NOT NULL,
    year_of_future_adt_115 integer NOT NULL,
    min_nav_clr_mt_116 double precision,
    fed_agency boolean NOT NULL,
    submitted_by integer NOT NULL,
    bridge_condition character varying NOT NULL,
    lowest_rating integer NOT NULL,
    deck_area double precision NOT NULL,
    status character varying NOT NULL,
    date integer NOT NULL,
    latdd double precision NOT NULL,
    longdd double precision NOT NULL,
    x double precision NOT NULL,
    y double precision NOT NULL,
    CONSTRAINT "pk_BRIDGE_INFO" PRIMARY KEY (objectid)--,
    --CONSTRAINT "fk_BRIDGE_INFO_state_code_001" FOREIGN KEY (state_code_001)
    --    REFERENCES public."STATE" (fips_code) MATCH SIMPLE
    --    ON UPDATE NO ACTION
    --    ON DELETE NO ACTION
)