-- Exported from QuickDBD: https://www.quickdatabasediagrams.com/
-- Link to schema: https://app.quickdatabasediagrams.com/#/d/5Hw5Pu
-- NOTE! If you have used non-SQL datatypes in your design, you will have to change these here.


CREATE TABLE "BRIDGE_INFO" (
    "objectid" int   NOT NULL,
    "state_code_001" varchar   NOT NULL,
    "structure_number_008" varchar   NOT NULL,
    "record_type_005a" int   NOT NULL,
    "route_prefix_005b" int   NOT NULL,
    "service_level_005c" int   NOT NULL,
    "route_number_005d" varchar   NOT NULL,
    "direction_005e" int   NOT NULL,
    "highway_district_002" varchar   NOT NULL,
    "county_code_003" varchar   NOT NULL,
    "place_code_004" varchar   NOT NULL,
    "features_desc_006a" varchar   NOT NULL,
    "critical_facility_006b" varchar   NOT NULL,
    "facility_carried_007" varchar   NOT NULL,
    "location_009" varchar   NOT NULL,
    "min_vert_clr_010" float   NOT NULL,
    "kilopoint_011" float   NOT NULL,
    "base_hwy_network_012" float   NOT NULL,
    "lrs_inv_route_013a" varchar   NOT NULL,
    "subroute_no_013b" float   NOT NULL,
    "lat_016" float   NOT NULL,
    "long_017" float   NOT NULL,
    "detour_kilos_019" int   NOT NULL,
    "toll_020" int   NOT NULL,
    "maintenance_021" varchar   NOT NULL,
    "owner_022" int   NOT NULL,
    "functional_class_026" varchar   NOT NULL,
    "year_built_027" int   NOT NULL,
    "traffic_lanes_on_028a" int   NOT NULL,
    "traffic_lanes_und_028B" int   NOT NULL,
    "adt_029" bigint   NOT NULL,
    "year_adt_030" float   NOT NULL,
    "design_load_031" varchar   NOT NULL,
    "appr_width_mt_032" float   NOT NULL,
    "median_code_033" int   NOT NULL,
    "degrees_skew_034" int   NOT NULL,
    "structure_flared_035" int   NOT NULL,
    "railings_036a" varchar   NOT NULL,
    "transitions_036b" varchar   NOT NULL,
    "appr_rail_036c" varchar   NOT NULL,
    "appr_rail_end_036d" varchar   NOT NULL,
    "history_037" int   NOT NULL,
    "navigation_038" varchar   NOT NULL,
    "nav_vert_clr_mt_039" float   NOT NULL,
    "nav_horr_clr_mt_040" float   NOT NULL,
    "open_closed_posted_041" varchar   NOT NULL,
    "service_on_042a" int   NOT NULL,
    "service_und_042b" int   NOT NULL,
    "structure_kind_043a" int   NOT NULL,
    "structure_type_043b" varchar   NOT NULL,
    "appr_kind_044a" int   NOT NULL,
    "apr_type_044b" varchar   NOT NULL,
    "main_unit_spans_045" int   NOT NULL,
    "appr_spans_046" int   NOT NULL,
    "horr_clr_mt_047" float   NOT NULL,
    "max_span_len_mt_048" float   NOT NULL,
    "structure_len_mt_049" float   NOT NULL,
    "left_curb_mt_050a" float   NOT NULL,
    "right_curb_mt_050b" float   NOT NULL,
    "roadway_width_mt_051" float   NOT NULL,
    "deck_width_mt_052" float   NOT NULL,
    "vert_clr_over_mt_053" float   NOT NULL,
    "vert_clr_und_ref_054a" varchar   NOT NULL,
    "vert_clr_und_054b" float   NOT NULL,
    "lat_und_ref_055a" varchar   NOT NULL,
    "lat_und_mt_055b" float   NOT NULL,
    "left_lat_und_mt_056" float   NOT NULL,
    "deck_cond_058" varchar   NOT NULL,
    "superstructure_cond_059" varchar   NOT NULL,
    "substructure_cond_060" varchar   NOT NULL,
    "channel_cond_061" varchar   NOT NULL,
    "culvert_cond_062" varchar   NOT NULL,
    "opr_rating_meth_063" varchar   NOT NULL,
    "operating_rating_064" float   NOT NULL,
    "inv_rating_meth_065" varchar   NOT NULL,
    "inventory_rating_066" float   NOT NULL,
    "structural_eval_067" varchar   NOT NULL,
    "deck_geometry_eval_068" varchar   NOT NULL,
    "undclrence_eval_069" varchar   NOT NULL,
    "posting_eval_070" float   NOT NULL,
    "waterway_eval_071" varchar   NOT NULL,
    "appr_road_eval_072" float   NOT NULL,
    "work_proposed_075a" float   NOT NULL,
    "work_done_by_075b" float   NOT NULL,
    "imp_len_mt_076" float   NOT NULL,
    "date_of_inspect_090" int   NOT NULL,
    "inspect_freq_months_091" int   NOT NULL,
    "fracture_092a" varchar   NOT NULL,
    "undwater_look_see_092b" varchar   NOT NULL,
    "spec_inspect_092c" varchar   NOT NULL,
    "fracture_last_date_093a" varchar   NOT NULL,
    "undwater_last_date_093b" varchar   NOT NULL,
    "spec_last_date_093c" varchar   NOT NULL,
    "bridge_imp_cost_094" float   NOT NULL,
    "roadway_imp_cost_095" float   NOT NULL,
    "total_imp_cost_096" float   NOT NULL,
    "year_of_imp_097" float   NOT NULL,
    "other_state_code_098a" varchar   NOT NULL,
    "other_state_pcnt_098b" float   NOT NULL,
    "othr_state_struc_no_099" varchar   NOT NULL,
    "strahnet_highway_100" int   NOT NULL,
    "parallel_structure_101" varchar   NOT NULL,
    "traffic_direction_102" int   NOT NULL,
    "temp_structure_103" varchar   NOT NULL,
    "highway_system_104" int   NOT NULL,
    "federal_lands_105" int   NOT NULL,
    "year_reconstructed_106" float   NOT NULL,
    "deck_structure_type_107" varchar   NOT NULL,
    "surface_type_108a" varchar   NOT NULL,
    "membrane_type_108b" varchar   NOT NULL,
    "deck_protection_108c" varchar   NOT NULL,
    "percent_adt_truck_109" float   NOT NULL,
    "national_network_110" int   NOT NULL,
    "pier_protection_111" float   NOT NULL,
    "bridge_len_ind_112" varchar   NOT NULL,
    "scour_critical_113" varchar   NOT NULL,
    "future_adt_114" bigint   NOT NULL,
    "year_of_future_adt_115" int   NOT NULL,
    "min_nav_clr_mt_116" float   NOT NULL,
    "fed_agency" Boolean   NOT NULL,
    "submitted_by" int   NOT NULL,
    "bridge_condition" varchar   NOT NULL,
    "lowest_rating" int   NOT NULL,
    "deck_area" float   NOT NULL,
    "status" varchar   NOT NULL,
    "date" int   NOT NULL,
    "latdd" float   NOT NULL,
    "longdd" float   NOT NULL,
    "x" float   NOT NULL,
    "y" float   NOT NULL,
    CONSTRAINT "pk_BRIDGE_INFO" PRIMARY KEY (
        "objectid"
     )
);

CREATE TABLE "STATE" (
    "fips_code" varchar   NOT NULL,
    "postal_abbr" varchar   NOT NULL,
    "state_name" varchar   NOT NULL,
    CONSTRAINT "pk_STATE" PRIMARY KEY (
        "fips_code"
     )
);

ALTER TABLE "BRIDGE_INFO" ADD CONSTRAINT "fk_BRIDGE_INFO_state_code_001" FOREIGN KEY("state_code_001")
REFERENCES "STATE" ("fips_code");

